### ISSUE TITLE
Hangs when I try to source it

### ISSUE THREAD

**Issue by rofrol** [dmy/elm-sh-completion#2]
```bash
~ $ . /etc/bash_completion.d/elm 
^C
~ $ bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by rlefevre** [comment]
Could you please run the script like this and copy/paste here the output:
```
bash -x /etc/bash_completion.d/elm 
```

**Comment by rofrol** [comment]
Works. I have elm in path when I run first `nvm`: https://github.com/rofrol/dotfiles/blob/master/.bashrc#L123

Should I close the issue?

**Comment by rlefevre** [comment]
Hmm, so elm was not in your PATH when it failed? It should not hang though :thinking: 

You can close if you think there is no issue.

**Comment by rofrol** [comment]
Maybe it should not hang when elm not in path. so there is still issue.

**Comment by rlefevre** [comment]
I agree, but I cannot reproduce the script hanging without elm in PATH. 

I have added an explicit check with an error message, this should avoid the issue and help users fixing the problem:
https://github.com/dmy/elm-sh-completion/commit/177fe295792704daf87e7ea5c144624b566190df

If you could confirm that it does not hang anymore without elm in PATH, this would be great.
If it still hangs, please reopen.

Thanks.

**Comment by rofrol** [comment]
The problem was the I had this in `$PATH`:

```
$ cat ~/bin/elm
#!/bin/bash
# https://discourse.elm-lang.org/t/working-around-not-enough-bytes-problems/3359/3
(
  flock -e 200
  #echo `which elm`
  elm $@
) 200>/tmp/elm.lockfile

**Comment by rlefevre** [comment]
> elm $@

I see, it will call itself and hangs on the lock. You should call `elm` inside the wrapper script with the full path, or remove `~/bin` from PATH before calling it.
